services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
      target: runtime
    container_name: health-backend
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          memory: 128M
    env_file: ./backend/.env
    environment:
      REDIS_HOST: "redis"
      REDIS_CERTS_DIR: "/run/secrets"
      REDIS_PORT: "6380"
      REDIS_DB: $REDIS_DB
    mem_swappiness: 0
    ports:
      - "8000:8000"
    restart: unless-stopped
    secrets:
      - source: ca.pem
      - source: app.pem
      - source: app.key
      - source: app_password

  docs-compiler:
    build:
      context: .
      dockerfile: docker/Dockerfile.docs
    container_name: health-docs
    restart: no
    volumes:
      - ./docs/build:/home/health/docs/build

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    container_name: health-frontend
    depends_on:
      backend:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          memory: 256M
    ports:
      - "5173:5173"
    restart: unless-stopped

  redis-init:
    build:
      context: .
      dockerfile: docker/Dockerfile.redis-init
    restart: no
    user: root
    volumes:
      - redis-data:/data

  redis:
    build:
      context: .
      dockerfile: docker/Dockerfile.redis
    cap_drop:
      - ALL
    container_name: health-redis
    depends_on:
      redis-init:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "0.50"      # max. 1 core
          memory: 1G        # hard limit
        reservations: # guaranteed
          cpus: "0.10"
          memory: 256M
    mem_swappiness: 0
    environment:
      REDIS_ARGS: >-
        --tls-port 6380
        --port 0
        --tls-auth-clients yes
        --tls-ca-cert-file /run/secrets/ca.pem
        --tls-cert-file /run/secrets/server.pem
        --tls-key-file /run/secrets/server.key
        --appendonly yes
        --maxmemory 900mb
        --maxmemory-policy allkeys-lfu
        --loglevel notice
        --aclfile /run/secrets/users.acl
    ports:
      - "${REDIS_HOST:-127.0.0.1}:${REDIS_PORT:?REDIS_PORT must be set}:6380"
    restart: unless-stopped
    secrets:
      - source: users.acl
      - source: ca.pem
      - source: server.pem
      - source: server.key
      - source: healthcheck.pem
      - source: healthcheck.key
      - source: app.pem
      - source: app.key
      - source: admin_password
      - source: app_password
      - source: healthcheck_password
      - source: insight_password
    security_opt:
      - apparmor:docker-default
      - no-new-privileges:true
      - seccomp:docker/seccomp-redis.json
    volumes:
      - redis-data:/data

  redisinsight:
    build:
      context: .
      dockerfile: docker/Dockerfile.redisinsight
    cap_drop:
      - ALL
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.05"
          memory: 128M
    container_name: health-redisinsight
    mem_swappiness: 0
    ports:
      - "${REDIS_HOST:-127.0.0.1}:${REDIS_INSIGHT_PORT:?REDIS_INSIGHT_PORT must be set}:5540"
    restart: unless-stopped
    secrets:
      - source: ca.pem
      - source: redisinsight.pem
      - source: redisinsight.key
    security_opt:
      - no-new-privileges:true
    volumes:
      - redisinsight-data:/data

  sandbox:
    build:
      context: .
      dockerfile: docker/Dockerfile.sandbox
    container_name: health-sandbox
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 4G
        reservations:
          cpus: "0.10"
          memory: 64M
    environment:
      REDIS_HOST: "redis"
      REDIS_CERTS_DIR: "/run/secrets"
      REDIS_PORT: "6380"
      REDIS_DB: $REDIS_DB
    mem_swappiness: 0
    restart: no
    secrets:
      - source: ca.pem
      - source: app.pem
      - source: app.key
      - source: app_password
    volumes:
      - ./output:/home/health/output
      - ./data:/home/health/data
      - ./data/export.zip:/home/health/data/export.zip:ro

  test-runner:
    build:
      context: .
      dockerfile: docker/Dockerfile.tests
    container_name: health-test-suite
    restart: no

secrets:
  users.acl:
    file: ${SECRETS_DIR}/users.acl
  # CERTIFICATES
  ca.pem:
    file: ${SECRETS_DIR}/ca.pem
  server.pem:
    file: ${SECRETS_DIR}/server.pem
  healthcheck.pem:
    file: ${SECRETS_DIR}/healthcheck.pem
  redisinsight.pem:
    file: ${SECRETS_DIR}/redisinsight.pem
  app.pem:
    file: ${SECRETS_DIR}/app.pem
  # KEYS
  server.key:
    file: ${SECRETS_DIR}/server.key
  healthcheck.key:
    file: ${SECRETS_DIR}/healthcheck.key
  redisinsight.key:
    file: ${SECRETS_DIR}/redisinsight.key
  app.key:
    file: ${SECRETS_DIR}/app.key
  # PASSWORDS
  admin_password:
    file: ${SECRETS_DIR}/admin_password
  healthcheck_password:
    file: ${SECRETS_DIR}/healthcheck_password
  insight_password:
    file: ${SECRETS_DIR}/insight_password
  app_password:
    file: ${SECRETS_DIR}/app_password

volumes:
  redis-data:
    driver: local
  redisinsight-data:
    driver: local
