services:
  backend:
    image: health-backend:dev
    volumes:
      - ./backend/apps:/home/health/apps:ro
      - ./backend/config:/home/health/config:ro
      - ./src:/home/health/src:ro

  frontend:
    image: health-frontend:dev

  sandbox:
    volumes:
      - ./src:/home/health/src:ro
      - ./scripts/setup_logger.py:/home/health/scripts/setup_logger.py:ro
      - ./scripts/import_to_redis.py:/home/health/scripts/import_to_redis.py:ro
