"""Parser for Apple Health export files.

Reads the export.zip produced by the Apple Health app and returns a single
tidy DataFrame that can be saved to by the caller.
"""

import zipfile
from pathlib import Path
from zoneinfo import ZoneInfo

import defusedxml.ElementTree as ETree
import pandas as pd


def parse_apple_health(zip_path: str | Path) -> pd.DataFrame:
    """Parse an Apple Health export archive into a DataFrame.

    Reads all Record elements from the export.xml inside the given export.zip
    and returns them as a single tidy DataFrame with timezone-aware datetime
    columns. The output schema is a superset of the one produced by
    apple-health-exporter's health_xml_to_feather, adding device, sourceVersion,
    and creationDate columns.

    Args:
        zip_path: Path to the export.zip file generated by the Apple Health app.

    Returns:
        A DataFrame with one row per health record and the following columns:

        - type (str): The HealthKit record type, e.g.
          ``HKQuantityTypeIdentifierHeartRate``.
        - sourceName (str): Human-readable name of the recording source, e.g.
          ``"Apple Watch"``.
        - sourceVersion (str): Version string of the recording source app.
        - device (str): Full device identifier string as reported by HealthKit.
        - unit (str): Unit of measurement, e.g. ``"count/min"`` or ``"kg"``.
        - startDate (datetime64[ns, Europe/Berlin]): Start of the recorded
          interval, converted to Europe/Berlin time.
        - endDate (datetime64[ns, Europe/Berlin]): End of the recorded interval,
          converted to Europe/Berlin time.
        - creationDate (datetime64[ns, Europe/Berlin]): When the record was
          created, converted to Europe/Berlin time.
        - value (str): The recorded value as a string, e.g. ``"72"`` or
          ``"5.6"``. Cast to a numeric type by the caller if needed.

    Example:
        >>> df = parse_apple_health("export.zip")
        >>> df.to_feather("data.feather")
        >>> heart_rate = df[df["type"] == "HKQuantityTypeIdentifierHeartRate"]
        >>> heart_rate["value"].astype(float).mean()

    """
    with (
        zipfile.ZipFile(zip_path) as zf,
        zf.open("apple_health_export/export.xml") as f,
    ):
        tree = ETree.parse(f)

    root = tree.getroot()

    rows = []
    for record in root.iter("Record"):
        a = record.attrib
        rows.append(
            {
                "type": a.get("type"),
                "sourceName": a.get("sourceName"),
                "sourceVersion": a.get("sourceVersion"),
                "device": a.get("device"),
                "unit": a.get("unit"),
                "startDate": a.get("startDate"),
                "endDate": a.get("endDate"),
                "creationDate": a.get("creationDate"),
                "value": a.get("value"),
            }
        )

    df = pd.DataFrame(rows)

    tz = ZoneInfo("Europe/Berlin")
    for col in ("startDate", "endDate", "creationDate"):
        df[col] = pd.to_datetime(df[col], utc=True).dt.tz_convert(tz)

    return df
