"""Parser for Apple Health export files.

Reads the export.zip produced by the Apple Health app and returns one tidy
DataFrame per top-level element type (records, correlations, workouts,
ActivitySummary entries) plus a helper for parsing workout-route GPX files.

Memory note
-----------
The :func:`parse_apple_health` function accumulates records using per-column
lists (one ``list`` per column in ``_RECORD_COLUMNS``) rather than a list of
per-row dicts.  This avoids creating a ``list[dict]`` intermediate structure
alongside the final DataFrame, cutting peak memory consumption roughly in half
for the records table (which may contain millions of rows).  Workout,
correlation, and activity rows are fewer in number so they retain the
list-of-dicts approach for readability.

Unknown elements
----------------
Top-level XML elements that this parser does not yet handle (``Me``,
``ExportDate``, ``ClinicalRecord``, ``Audiogram``, ``VisionPrescription`` …)
emit a ``WARNING`` once per tag with the total count at end-of-parse so that
silent data drops are visible to operators.  Unknown *child* elements raise
``NotImplementedError`` rather than being skipped — the parser is opinionated
that schema drift inside a known parent indicates a real change worth halting
on.
"""

from __future__ import annotations

import logging
import zipfile
from collections import Counter
from pathlib import Path

import defusedxml.ElementTree as ETree
import pandas as pd

logger = logging.getLogger(__name__)

# columns of parse_apple_health output dfs
_RECORD_COLUMNS = (
    "type",
    "sourceName",
    "sourceVersion",
    "device",
    "unit",
    "startDate",
    "endDate",
    "creationDate",
    "value",
)

_CORRELATION_COLUMNS = (
    "sourceName",
    "endDate",
    "startDate",
    "sourceVersion",
    "type",
    "creationDate",
    "meta",
    "records",
)

_ACTIVITY_COLUMNS = (
    "dateComponents",
    "appleExerciseTime",
    "appleMoveTime",
    "activeEnergyBurnedGoal",
    "activeEnergyBurnedUnit",
    "appleStandHoursGoal",
    "appleMoveTimeGoal",
    "appleStandHours",
    "activeEnergyBurned",
    "appleExerciseTimeGoal",
)

_WORKOUT_COLUMNS = (
    "sourceName",
    "endDate",
    "duration",
    "startDate",
    "durationUnit",
    "sourceVersion",
    "creationDate",
    "device",
    "workoutActivityType",
    "meta",
    "events",
    "statistics",
    "route",
    "activities",
)

# keys of workout dicts
_WORKOUT_ACTIVITY_KEYS = [
    "endDate",
    "duration",
    "startDate",
    "durationUnit",
    "uuid",
    "meta",
    "statistics",
    "events",
]
_WORKOUT_EVENT_KEYS = ["durationUnit", "date", "duration", "type"]
_WORKOUT_ROUTE_KEYS = [
    "sourceName",
    "endDate",
    "startDate",
    "sourceVersion",
    "creationDate",
    "device",
]
_WORKOUT_STATISTICS_KEYS = [
    "endDate",
    "sum",
    "startDate",
    "type",
    "minimum",
    "unit",
    "maximum",
    "average",
]

# Top-level element tags that Apple Health emits but this parser does not
# convert to DataFrames.  Listed explicitly so the WARNING message can name
# the well-known cases instead of repeating "unknown element".
_KNOWN_UNHANDLED_TAGS = frozenset(
    {
        "ExportDate",
        "Me",
        "ClinicalRecord",
        "Audiogram",
        "VisionPrescription",
    }
)


class NoHealthDataError(ValueError):
    """Raised when trying to parse a zip file without usable data."""

    pass


def parse_apple_health(
    zip_path: str | Path,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Parse an Apple Health export archive into a collection of DataFrames.

    Reads the export.xml inside the given export.zip using a memory-efficient
    streaming parser and returns one DataFrame per top-level element type.
    Unknown *child* elements raise ``NotImplementedError`` (silent schema
    drift inside a known parent would corrupt downstream uploads).  Unknown
    *top-level* elements are logged at WARNING level with a per-tag count at
    end-of-parse so operators see the gap without halting the run.

    Memory optimisation: the records DataFrame is built from per-column lists
    rather than a list-of-row-dicts, avoiding a large intermediate allocation.

    Args:
        zip_path: Path to the export.zip file generated by the Apple Health app.
            Accepts both :class:`str` and :class:`pathlib.Path`.

    Returns:
        A 4-tuple of ``(records, correlations, workouts, activities)``:

        **records** — one row per ``Record`` element not belonging to a
        ``Correlation``. Columns follow ``_RECORD_COLUMNS``
        (type, sourceName, sourceVersion, device, unit, startDate, endDate,
        creationDate, value). All values are strings as exported; numeric
        conversion is left to the caller.

        **correlations** — one row per ``Correlation`` element. Columns follow
        ``_CORRELATION_COLUMNS`` plus:

        - meta (dict): ``MetadataEntry`` children as ``{key: value}``.
        - records (list[dict]): nested ``Record`` elements, each with
          ``_RECORD_COLUMNS`` fields.

        **workouts** — one row per ``Workout`` element. Columns follow
        ``_WORKOUT_COLUMNS`` plus:

        - meta (dict): ``MetadataEntry`` children as ``{key: value}``.
        - events (list[dict]): ``WorkoutEvent`` elements with
          ``_WORKOUT_EVENT_KEYS`` fields and any ``MetadataEntry`` children
          merged in as extra keys.
        - statistics (list[dict]): ``WorkoutStatistics`` elements with
          ``_WORKOUT_STATISTICS_KEYS`` fields.
        - route (dict | None): ``WorkoutRoute`` attributes from
          ``_WORKOUT_ROUTE_KEYS`` plus ``files`` (list of GPX file paths)
          and ``meta`` (dict of ``MetadataEntry`` children); ``None`` if no
          route is present.
        - activities (list[dict]): ``WorkoutActivity`` elements, each with
          ``_WORKOUT_ACTIVITY_KEYS`` fields plus ``meta`` (dict), ``events``
          (list[dict]) and ``statistics`` (list[dict]) using the same
          structure as the workout-level fields above.

        **activities** — one row per ``ActivitySummary`` element. Columns
        follow ``_ACTIVITY_COLUMNS``.

    Raises:
        NoHealthDataError: If all four returned DataFrames are empty, i.e. the
            archive contained no recognisable health data.
        NotImplementedError: If an element has a child element that is not yet
            handled by the parser.

    Example:
        >>> records, corr, workouts, activities = parse_apple_health("export.zip")
        >>> records.to_feather("records.feather")
        >>> heart_rate = records[records["type"] == "HKQuantityTypeIdentifierHeartRate"]
        >>> heart_rate["value"].astype(float).mean()

    """
    # Per-column lists for records — avoids list-of-dicts intermediate.
    record_cols: dict[str, list[str]] = {col: [] for col in _RECORD_COLUMNS}
    correlation_rows: list[
        dict[str, str | dict[str, str | None] | list[dict[str, str | None]] | None]
    ] = []
    workout_rows: list[
        dict[
            str,
            str
            | None
            | list[
                dict[
                    str,
                    str | dict[str, str | None] | list[dict[str, str | None]] | None,
                ]
            ]
            | list[dict[str, str | None]]
            | dict[str, str | None]
            | list[dict[str, str | list[str] | dict[str, str | None] | None]]
            | list[dict[str, str | None]],
        ]
    ] = []
    activity_rows: list[dict[str, str | None]] = []
    unknown_counts: Counter[str] = Counter()

    with (
        zipfile.ZipFile(zip_path) as zf,
        zf.open("apple_health_export/export.xml") as f,
    ):
        root = None
        correlation = False
        for event, elem in ETree.iterparse(f, events=("start", "end")):
            if event == "start":
                if root is None:
                    root = elem
                elif elem.tag == "Correlation":
                    correlation = True
                continue

            # event == "end"
            match elem.tag:
                case "Record":
                    if correlation:
                        # Belongs to a parent Correlation; processed there.
                        continue
                    # Columnar accumulation — one list append per column.
                    # Hoist attrib lookup once per record to skip repeated
                    # attribute access through the C extension.
                    attrib = elem.attrib
                    for col in _RECORD_COLUMNS:
                        record_cols[col].append(attrib.get(col))

                case "Correlation":
                    corr: dict[
                        str,
                        str
                        | dict[str, str | None]
                        | list[dict[str, str | None]]
                        | None,
                    ] = {col: elem.attrib.get(col) for col in _CORRELATION_COLUMNS}
                    meta_co: dict[str, str | None] = {}
                    records: list[dict[str, str | None]] = []
                    for child in elem:
                        match child.tag:
                            case "MetadataEntry":
                                if c := child.attrib.get("key"):
                                    meta_co[c] = child.attrib.get("value")
                            case "Record":
                                records.append(
                                    {
                                        col: child.attrib.get(col)
                                        for col in _RECORD_COLUMNS
                                    }
                                )
                            case _:
                                raise NotImplementedError(
                                    f"{elem.tag} child {child.tag} is not implemented."  # noqa: E501
                                )

                    corr["meta"] = meta_co
                    corr["records"] = records
                    correlation_rows.append(corr)
                    correlation = False

                case "Workout":
                    workout: dict[
                        str,
                        str
                        | None
                        | list[
                            dict[
                                str,
                                str
                                | dict[str, str | None]
                                | list[dict[str, str | None]]
                                | None,
                            ]
                        ]
                        | list[dict[str, str | None]]
                        | dict[str, str | None]
                        | list[
                            dict[str, str | list[str] | dict[str, str | None] | None]
                        ]
                        | list[dict[str, str | None]],
                    ] = {col: elem.attrib.get(col) for col in _WORKOUT_COLUMNS}

                    activities: list[
                        dict[
                            str,
                            str
                            | dict[str, str | None]
                            | list[dict[str, str | None]]
                            | None,
                        ]
                    ] = []
                    events: list[dict[str, str | None]] = []
                    meta_wo: dict[str, str | None] = {}
                    route: list[
                        dict[str, str | list[str] | dict[str, str | None] | None]
                    ] = []
                    stats: list[dict[str, str | None]] = []
                    for child in elem:
                        match child.tag:
                            case "WorkoutActivity":
                                activity: dict[
                                    str,
                                    str
                                    | dict[str, str | None]
                                    | list[dict[str, str | None]]
                                    | None,
                                ] = {
                                    col: child.attrib.get(col)
                                    for col in _WORKOUT_ACTIVITY_KEYS
                                }

                                e_wo: list[dict[str, str | None]] = []
                                m_wo: dict[str, str | None] = {}
                                s_wo: list[dict[str, str | None]] = []
                                for c in child:
                                    match c.tag:
                                        case "WorkoutEvent":
                                            _e: dict[str, str | None] = {
                                                col: c.attrib.get(col)
                                                for col in _WORKOUT_EVENT_KEYS
                                            }
                                            for _c in c:
                                                if _c.tag == "MetadataEntry" and (
                                                    _k := _c.attrib.get("key")
                                                ):
                                                    _e[_k] = _c.attrib.get("value")
                                                else:
                                                    raise NotImplementedError(
                                                        f"{c.tag} child {_c.tag} is not implemented."  # noqa: E501
                                                    )
                                            e_wo.append(_e)
                                        case "MetadataEntry":
                                            if k := c.attrib.get("key"):
                                                m_wo[k] = c.attrib.get("value")
                                        case "WorkoutStatistics":
                                            s_wo.append(
                                                {
                                                    col: c.attrib.get(col)
                                                    for col in _WORKOUT_STATISTICS_KEYS  # noqa: E501
                                                }
                                            )
                                        case _:
                                            raise NotImplementedError(
                                                f"{child.tag} child {c.tag} is not implemented."  # noqa: E501
                                            )

                                activity["meta"] = m_wo
                                activity["statistics"] = s_wo
                                activity["events"] = e_wo
                                activities.append(activity)

                            case "WorkoutEvent":
                                we: dict[str, str | None] = {
                                    col: child.attrib.get(col)
                                    for col in _WORKOUT_EVENT_KEYS
                                }
                                for c in child:
                                    if c.tag == "MetadataEntry" and (
                                        k := c.attrib.get("key")
                                    ):
                                        we[k] = c.attrib.get("value")
                                    else:
                                        raise NotImplementedError(
                                            f"{child.tag} child {c.tag} is not implemented."  # noqa: E501
                                        )
                                events.append(we)

                            case "MetadataEntry":
                                if k := child.attrib.get("key"):
                                    meta_wo[k] = child.attrib.get("value")

                            case "WorkoutRoute":
                                r: dict[
                                    str, str | list[str] | dict[str, str | None] | None
                                ] = {
                                    col: child.attrib.get(col)
                                    for col in _WORKOUT_ROUTE_KEYS
                                }

                                files: list[str] = []
                                m_wr: dict[str, str | None] = {}
                                for c in child:
                                    match c.tag:
                                        case "FileReference":
                                            if p := c.attrib.get("path"):
                                                files.append(p)
                                        case "MetadataEntry":
                                            if k := c.attrib.get("key"):
                                                m_wr[k] = c.attrib.get("value")
                                        case _:
                                            raise NotImplementedError(
                                                f"{child.tag} child {c.tag} is not implemented."  # noqa: E501
                                            )
                                r["files"] = files
                                r["meta"] = m_wr
                                route.append(r)

                            case "WorkoutStatistics":
                                stats.append(
                                    {
                                        col: child.attrib.get(col)
                                        for col in _WORKOUT_STATISTICS_KEYS
                                    }
                                )

                            case _:
                                raise NotImplementedError(
                                    f"{elem.tag} child {child.tag} is not implemented."  # noqa: E501
                                )

                    workout["meta"] = meta_wo
                    workout["events"] = events
                    workout["statistics"] = stats
                    workout["route"] = route
                    workout["activities"] = activities
                    workout_rows.append(workout)

                case "ActivitySummary":
                    activity_rows.append(
                        {col: elem.attrib.get(col) for col in _ACTIVITY_COLUMNS}
                    )

                case _:
                    # Unknown top-level element — record it but do not abort.
                    # `root` is non-None at this point because the very first
                    # `start` event sets it; the explicit guard satisfies
                    # static analysis without changing behaviour.
                    if root is not None and elem is root:
                        # Closing tag of <HealthData> — nothing to count.
                        continue
                    unknown_counts[elem.tag] += 1

            # Free memory of the just-finished top-level child of root.
            # Done unconditionally so unknown elements do not accumulate
            # while waiting for the next known one to trigger a clear.
            if root is not None and elem is not root:
                root.clear()

    if unknown_counts:
        _log_unknown_elements(unknown_counts)

    record_df = pd.DataFrame(record_cols)
    correlation_df = pd.DataFrame(correlation_rows)
    workout_df = pd.DataFrame(workout_rows)
    activity_df = pd.DataFrame(activity_rows)

    if (
        record_df.empty
        and correlation_df.empty
        and workout_df.empty
        and activity_df.empty
    ):
        logger.error("No records found in zip file %s.", zip_path)
        raise NoHealthDataError

    logger.info(
        "Parsed %d records, %d correlations, %d workouts, %d activity summaries.",
        len(record_df),
        len(correlation_df),
        len(workout_df),
        len(activity_df),
    )
    return record_df, correlation_df, workout_df, activity_df


def _log_unknown_elements(counts: Counter[str]) -> None:
    """Emit a single WARNING summarising unhandled top-level elements.

    Known-but-unhandled tags (``Me``, ``ExportDate`` …) and genuinely
    unknown tags are reported together with their occurrence counts so a
    new HealthKit element introduced by Apple in a future iOS release
    becomes immediately visible in the import log.
    """
    parts = []
    for tag, count in sorted(counts.items()):
        marker = "" if tag in _KNOWN_UNHANDLED_TAGS else " (unrecognised)"
        parts.append(f"{tag}={count}{marker}")
    logger.warning("Skipped unhandled top-level element(s): %s", ", ".join(parts))


_GPX_NS = "http://www.topografix.com/GPX/1/1"
_GPX_EXT_FIELDS = ("speed", "course", "hAcc", "vAcc")


def parse_apple_health_routes(
    zip_path: str | Path,
    paths: list[str] | None = None,
) -> pd.DataFrame:
    """Parse workout-route GPX files from an Apple Health export archive.

    Each workout route is stored as a separate GPX file inside the archive.
    File paths are available on the ``route["files"]`` field of rows
    returned by :func:`parse_apple_health`.  If no paths are given, every
    ``workout-routes/*.gpx`` file in the archive is parsed.

    The returned DataFrame is one row per trackpoint, with a ``file``
    column that lets the caller join trackpoints back to their workout via
    the route ``files`` list.

    Args:
        zip_path: Path to the export.zip file generated by the Apple Health
            app.  Accepts both :class:`str` and :class:`pathlib.Path`.
        paths: Optional list of GPX file paths relative to the
            ``apple_health_export/`` directory inside the archive, e.g.
            ``["workout-routes/route_2024-03-15_123456789.gpx"]``.  If
            ``None``, all ``workout-routes/*.gpx`` files are parsed.

    Returns:
        A DataFrame with one row per trackpoint and the following columns:

        - file (str): GPX file path relative to ``apple_health_export/``.
        - lat (float): Latitude in degrees (WGS84).
        - lon (float): Longitude in degrees (WGS84).
        - ele (float | None): Altitude in metres above sea level.
        - time (datetime64[ns, UTC]): UTC timestamp of the sample.
        - speed (float | None): Instantaneous speed in m/s.
        - course (float | None): Heading in degrees (0–360).
        - hAcc (float | None): Horizontal accuracy in metres.
        - vAcc (float | None): Vertical accuracy in metres.

    Example:
        >>> records, corr, workouts, activities = parse_apple_health("export.zip")
        >>> route_paths = [
        ...     path
        ...     for route in workouts["route"].dropna()
        ...     for path in route["files"]
        ... ]
        >>> routes = parse_apple_health_routes("export.zip", paths=route_paths)
        >>> routes.head()

    """
    rows = []

    with zipfile.ZipFile(zip_path) as zf:
        if paths is None:
            paths = [
                name.removeprefix("apple_health_export/")
                for name in zf.namelist()
                if name.startswith("apple_health_export/workout-routes/")
                and name.endswith(".gpx")
            ]

        for path in paths:
            with zf.open(f"apple_health_export/{path}") as f:
                for _, elem in ETree.iterparse(f, events=("end",)):
                    if elem.tag != f"{{{_GPX_NS}}}trkpt":
                        continue

                    row: dict[str, object] = {
                        "file": path,
                        "lat": float(elem.attrib["lat"]),
                        "lon": float(elem.attrib["lon"]),
                    }

                    ele = elem.find(f"{{{_GPX_NS}}}ele")
                    row["ele"] = float(ele.text) if ele is not None else None

                    time_elem = elem.find(f"{{{_GPX_NS}}}time")
                    row["time"] = time_elem.text if time_elem is not None else None

                    ext = elem.find(f"{{{_GPX_NS}}}extensions")
                    for field in _GPX_EXT_FIELDS:
                        child = None
                        if ext is not None:
                            child = ext.find(field) or ext.find(f"{{{_GPX_NS}}}{field}")
                        row[field] = float(child.text) if child is not None else None

                    rows.append(row)
                    elem.clear()

    df = pd.DataFrame(rows)
    if not df.empty:
        df["time"] = pd.to_datetime(df["time"], utc=True)
    return df
