services:
  backend:
    image: health-backend:prod
    volumes:
      - uv-runtime-cache:/home/health/.cache/uv
  backend-dev:
    image: health-backend:dev
    volumes:
      - ./backend/apps:/home/health/apps:ro
      - ./backend/config:/home/health/config:ro
      - ./src:/home/health/src:ro
      - uv-runtime-cache:/home/health/.cache/uv
  backend-test:
    image: health-backend:test
    volumes:
      - uv-runtime-cache:/home/health/.cache/uv
  docs-compiler:
    image: health-docs
    volumes:
      - ./docs/build:/home/health/docs/build
      - ./docs/source:/home/health/docs/source
      - uv-runtime-cache:/home/health/.cache/uv
  frontend:
    image: health-frontend:prod
  frontend-dev:
    image: health-frontend:dev
  frontend-test:
    image: health-frontend:test
  sandbox:
    volumes:
      - ./src:/home/health/src:ro
      - ./scripts/setup_logger.py:/home/health/setup_logger.py:ro
      - ./scripts/import_to_redis.py:/home/health/import_to_redis.py:ro
      - uv-runtime-cache:/home/health/.cache/uv
  test-runner:
    volumes:
      - uv-runtime-cache:/home/health/.cache/uv
volumes:
  uv-runtime-cache:
    driver: local
