# syntax=docker/dockerfile:1.28@sha256:bb22d9815c728170f72750f4e5b0d672e06176142e1d602c7e66c050100b7e5b
FROM redis/redis-stack-server:7.4.0-v8@sha256:798ab84d9f266936b034ab11c4d04a2b8e4b441884c5aa7d17ac951eefdf742a

# Update system dependencies
RUN rm -f /etc/apt/apt.conf.d/docker-clean && \
    echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' \
      > /etc/apt/apt.conf.d/keep-cache

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && apt-get install --yes --no-install-recommends openssl && apt-get dist-upgrade --yes -V

# create user
RUN useradd --create-home --uid 1000 health
USER health
WORKDIR /home/health/

CMD ["/entrypoint.sh"]

HEALTHCHECK --interval=1m --timeout=5s --retries=5 --start-period=60s --start-interval=5s \
    CMD sh -c 'output=$(redis-cli \
        -p 6380 \
        --tls \
        --cacert /run/secrets/ca.pem \
        --cert   /run/secrets/healthcheck.pem \
        --key    /run/secrets/healthcheck.key \
        --user healthcheck \
        -a "$(cat /run/secrets/healthcheck_password)" \
        --no-auth-warning \
        ping 2>&1); \
        echo "$output"; \
        echo "$output" | grep -q PONG'
