# syntax=docker/dockerfile:1.7
# dockerfile for test-runner
FROM python:3.12-slim-bookworm@sha256:58525e1a8dada8e72d6f8a11a0ddff8d981fd888549108db52455d577f927f77

# Install system dependencies
RUN apt update && apt dist-upgrade -y -V && rm -rf /var/lib/apt/lists/*

# create user
RUN useradd --create-home --uid 1000 health
USER health
WORKDIR /home/health/

# Install requirements
COPY --chown=health:health ./tests/requirements.txt .
COPY --chown=health:health ./pip-requirements.txt .
ENV PATH="/home/health/.local/bin:$PATH"
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --user --require-hashes -r pip-requirements.txt && \
    pip install --user --require-hashes -r requirements.txt

COPY --chown=health:health ./src ./src
COPY --chown=health:health ./tests .
COPY --chown=health:health ./pyproject.toml .

ENTRYPOINT ["python3", "-m", "pytest", "--cov=src"]
