FROM node:26.1.0-alpine@sha256:e71ac5e964b9201072425d59d2e876359efa25dc96bb1768cb73295728d6e4ea AS base

RUN mkdir -p /app && chown node:node /app
WORKDIR /app
COPY --chown=node:node ./frontend .
COPY --chown=node:node ./versions.json .
RUN --mount=type=cache,target=/root/.npm npm ci --omit=dev
USER node

FROM base AS dev-base
USER root
RUN --mount=type=cache,target=/root/.npm \
    npm ci
USER node

FROM dev-base AS dev
HEALTHCHECK --interval=30s --timeout=5s --retries=3 --start-period=20s --start-interval=5s \
    CMD wget --spider -q http://localhost:5173
CMD ["npm", "run", "dev", "--", "--host"]

FROM dev-base AS test
ENTRYPOINT ["npm", "run", "test:coverage", "--"]

FROM dev-base AS builder
RUN --mount=type=cache,target=/app/node_modules/.cache npm run build

FROM nginx:1.29.8-alpine@sha256:5616878291a2eed594aee8db4dade5878cf7edcb475e59193904b198d9b830de AS prod
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
HEALTHCHECK --interval=30s --timeout=5s --retries=3 --start-period=10s \
    CMD wget --spider -q http://localhost:80 || exit 1
