FROM node:25-alpine@sha256:bdf2cca6fe3dabd014ea60163eca3f0f7015fbd5c7ee1b0e9ccb4ced6eb02ef4

WORKDIR /app
COPY --chown=node:node ./frontend/package*.json .
RUN --mount=type=cache,target=/app/node_modules/.cache npm install
COPY --chown=node:node ./frontend .

HEALTHCHECK --interval=30s --timeout=5s --retries=3 --start-period=20s --start-interval=5s \
    CMD wget --spider -q http://localhost:5173

USER node
