# syntax=docker/dockerfile:1.27@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e
FROM ghcr.io/astral-sh/uv:0.12.10-python3.12-trixie-slim@sha256:4bf11151c225e2a4d60e2a576b67d925660055199389d9a64fbdc02b6f3d43d5 AS base

RUN useradd --create-home --uid 1000 health
RUN mkdir -p /home/health/.cache/uv && chown -R health:health /home/health
USER health
WORKDIR /home/health

ENV UV_CACHE_DIR=/home/health/.cache/uv \
    UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=1 \
    UV_PYTHON_DOWNLOADS=never \
    PYTHONUNBUFFERED=1 \
    PATH="/home/health/.venv/bin:$PATH"

# Dependency layer
COPY --chown=health:health pyproject.toml uv.lock ./
RUN --mount=type=cache,target=/home/health/.cache/uv,uid=1000,gid=1000,sharing=shared \
    uv sync --locked --no-dev --group test --no-install-project

# Project layer
COPY --chown=health:health ./src ./src
COPY --chown=health:health versions.json README.md ./
RUN --mount=type=cache,target=/home/health/.cache/uv,uid=1000,gid=1000,sharing=shared \
    uv sync --locked --no-dev --group test --no-editable


FROM base AS src-test
COPY --chown=health:health ./tests ./tests
ENTRYPOINT ["uv", "run", "--frozen", "-m", "pytest"]
CMD ["--cov=src", "--cov-report=term-missing:skip-covered", "--cov-fail-under=80"]


FROM base AS scripts-test
COPY --chown=health:health ./scripts ./scripts
ENTRYPOINT ["uv", "run", "--frozen", "-m", "pytest"]
