# syntax=docker/dockerfile:1.25@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12
FROM ghcr.io/astral-sh/uv:0.11.23-python3.12-trixie-slim@sha256:bf72061021b1039aff0aee1c73da3f54e845b318502c3f5382e1c704dd800ba8 AS base

RUN useradd --create-home --uid 1000 health
RUN mkdir -p /home/health/.cache/uv && chown -R health:health /home/health
USER health
WORKDIR /home/health

ENV UV_CACHE_DIR=/home/health/.cache/uv \
    UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=1 \
    UV_PYTHON_DOWNLOADS=never \
    PYTHONUNBUFFERED=1 \
    PATH="/home/health/.venv/bin:$PATH"

# Dependency layer
COPY --chown=health:health pyproject.toml uv.lock ./
RUN --mount=type=cache,target=/home/health/.cache/uv,uid=1000,gid=1000,sharing=shared \
    uv sync --locked --no-dev --group test --no-install-project

# Project layer
COPY --chown=health:health ./src ./src
COPY --chown=health:health versions.json README.md ./
RUN --mount=type=cache,target=/home/health/.cache/uv,uid=1000,gid=1000,sharing=shared \
    uv sync --locked --no-dev --group test --no-editable


FROM base AS src-test
COPY --chown=health:health ./tests ./tests
ENTRYPOINT ["uv", "run", "--frozen", "-m", "pytest"]
CMD ["--cov=src", "--cov-report=term-missing:skip-covered", "--cov-fail-under=80"]


FROM base AS scripts-test
COPY --chown=health:health ./scripts ./scripts
ENTRYPOINT ["uv", "run", "--frozen", "-m", "pytest"]
