"""Shared pytest configuration and fixtures for scripts test suite.

This conftest provides only fixtures that are genuinely cross-cutting:
filesystem and environment plumbing.  Module-specific stubs (e.g. patching
``get_uv`` or restoring ``REPORTS``) live in the respective test files,
where the coupling to the module under test is explicit.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# Make the scripts package importable.
#
# The repo layout is:
#   <repo_root>/
#     scripts/
#       ci/requirements_maintenance/*.py
#       tests/conftest.py              <-- this file
#
# Tests import via ``scripts.ci.requirements_maintenance.X`` so the *parent*
# of ``scripts/`` (``<repo_root>``) needs to be on ``sys.path``.  Pytest
# normally adds rootdir automatically; we add it explicitly as a belt-and-
# braces measure so the tests work no matter where pytest is invoked from.
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture()
def tmp_cwd(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Change the working directory to a fresh temporary directory."""
    monkeypatch.chdir(tmp_path)
    return tmp_path


@pytest.fixture()
def github_output(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    """Point GITHUB_OUTPUT at a temp file; return a helper that reads it."""
    out_file = tmp_path / "github_output.txt"
    out_file.touch()
    monkeypatch.setenv("GITHUB_OUTPUT", str(out_file))

    def read_outputs() -> dict[str, str]:
        pairs: dict[str, str] = {}
        for line in out_file.read_text().splitlines():
            if "=" in line:
                k, v = line.split("=", 1)
                pairs[k] = v
        return pairs

    return read_outputs


@pytest.fixture()
def reports_dir(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Create a REPORTS_DIR and point the env var at it; return its Path."""
    rd = tmp_path / "reports"
    rd.mkdir()
    monkeypatch.setenv("REPORTS_DIR", str(rd))
    return rd


# ---------------------------------------------------------------------------
# Helpers (importable from test files)
# ---------------------------------------------------------------------------


def make_in_file(directory: Path, name: str, includes: list[str] | None = None) -> Path:
    """Write a minimal .in file, optionally with ``-r`` includes."""
    lines = ["# generated by test\nrequests\n"]
    for inc in includes or []:
        lines.append(f"-r {inc}\n")
    path = directory / name
    path.write_text("".join(lines))
    return path


def make_txt_file(
    directory: Path, name: str, pins: dict[str, str] | None = None
) -> Path:
    """Write a minimal compiled .txt lockfile."""
    lines = [
        "# This file is autogenerated by pip-compile\n",
        "#\n",
    ]
    for pkg, ver in (pins or {"requests": "2.31.0"}).items():
        lines.append(f"{pkg}=={ver}\n")
    path = directory / name
    path.write_text("".join(lines))
    return path
