"""Tests for check_updates.py — dependency update detection.

Security focus: ``compile_upgraded`` must not invoke a shell; ``parse_pins``
must be linear-time in the size of input (no catastrophic backtracking on
adversarial regex input).

Safety focus: malformed lockfiles must not crash the parser; ``main`` must
faithfully aggregate per-file results.
"""

from __future__ import annotations

import json
import sys
import textwrap
import time
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import scripts.ci.requirements_maintenance.check_updates as check_updates  # noqa: E402

# ---------------------------------------------------------------------------
# Module-local fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(autouse=True)
def _stub_uv(monkeypatch):
    """Replace ``get_uv()`` with a no-op so tests don't require uv on PATH."""
    monkeypatch.setattr(check_updates, "get_uv", lambda: "uv")


@pytest.fixture(autouse=True)
def _restore_reports():
    """Restore ``check_updates.REPORTS`` after every test."""
    original = check_updates.REPORTS
    yield
    check_updates.REPORTS = original


# ---------------------------------------------------------------------------
# parse_pins
# ---------------------------------------------------------------------------


class TestParsePins:
    def test_simple_pin(self):
        pins = check_updates.parse_pins("requests==2.28.0\n")
        assert pins["requests"] == "2.28.0"

    def test_multiple_pins(self):
        text = "requests==2.28.0\nflask==3.0.0\ngunicorn==21.2.0\n"
        pins = check_updates.parse_pins(text)
        assert pins["flask"] == "3.0.0"
        assert pins["gunicorn"] == "21.2.0"

    def test_strips_inline_comment(self):
        pins = check_updates.parse_pins("requests==2.28.0  # via -r requirements.in\n")
        assert pins["requests"] == "2.28.0"

    def test_strips_env_marker(self):
        pins = check_updates.parse_pins('requests==2.28.0; python_version >= "3.8"\n')
        assert pins["requests"] == "2.28.0"

    def test_case_insensitive_key(self):
        pins = check_updates.parse_pins("Requests==2.28.0\n")
        assert "requests" in pins

    def test_ignores_hash_lines(self):
        text = textwrap.dedent("""\
            requests==2.28.0 \\
                --hash=sha256:abcdef1234567890
        """)
        pins = check_updates.parse_pins(text)
        assert "hash" not in pins
        assert "--hash" not in pins

    def test_ignores_comment_lines(self):
        pins = check_updates.parse_pins(
            "# This file is autogenerated\nrequests==2.28.0\n"
        )
        assert len(pins) == 1

    def test_ignores_empty_lines(self):
        pins = check_updates.parse_pins("\n\n\nrequests==2.28.0\n\n")
        assert len(pins) == 1

    def test_ignores_non_pin_entries(self):
        pins = check_updates.parse_pins(
            "-r base.txt\n--index-url https://pypi.org\nrequests==2.28.0\n"
        )
        assert "requests" in pins
        assert len(pins) == 1

    def test_empty_string_returns_empty_dict(self):
        assert check_updates.parse_pins("") == {}

    def test_normalises_package_name_with_dash(self):
        pins = check_updates.parse_pins("my-package==1.0\n")
        assert "my-package" in pins

    def test_version_with_dots(self):
        pins = check_updates.parse_pins("numpy==1.24.3\n")
        assert pins["numpy"] == "1.24.3"

    def test_version_with_plus_local_segment(self):
        """PEP 440 local versions like 1.0+local should parse."""
        pins = check_updates.parse_pins("pkg==1.0+local\n")
        assert "pkg" in pins

    def test_crlf_line_endings(self):
        """Windows-style line endings must parse identically to LF."""
        pins = check_updates.parse_pins("requests==2.28.0\r\nflask==3.0.0\r\n")
        assert pins == {"requests": "2.28.0", "flask": "3.0.0"}

    def test_duplicate_package_last_wins(self):
        """If a package is pinned twice, the later occurrence overrides.

        This is the dict-update semantics of the implementation; tested
        here so a future refactor (e.g. raise on duplicate) is deliberate.
        """
        pins = check_updates.parse_pins("requests==1.0\nrequests==2.0\n")
        assert pins == {"requests": "2.0"}

    def test_large_lockfile_performance(self):
        """Parsing 500 pins should complete well under one second."""
        lines = [f"package{i}=={i}.0.0" for i in range(500)]
        text = "\n".join(lines) + "\n"
        start = time.monotonic()
        pins = check_updates.parse_pins(text)
        elapsed = time.monotonic() - start
        assert len(pins) == 500
        assert elapsed < 0.5

    def test_pathological_input_does_not_hang(self):
        """A very long non-matching line must not trigger pathological backtracking."""
        text = "a" * 100_000 + "==1.0\n"  # eventually matches at the end
        start = time.monotonic()
        check_updates.parse_pins(text)
        elapsed = time.monotonic() - start
        assert elapsed < 1.0


# ---------------------------------------------------------------------------
# diff_pins
# ---------------------------------------------------------------------------


class TestDiffPins:
    def test_no_change_returns_empty(self):
        current = {"requests": "2.28.0", "flask": "3.0.0"}
        assert check_updates.diff_pins(current, current.copy()) == []

    def test_detects_upgrade(self):
        changes = check_updates.diff_pins(
            {"requests": "2.28.0"}, {"requests": "2.31.0"}
        )
        assert len(changes) == 1
        assert changes[0]["package"] == "requests"
        assert changes[0]["current"] == "2.28.0"
        assert changes[0]["latest"] == "2.31.0"

    def test_detects_new_package(self):
        changes = check_updates.diff_pins({}, {"requests": "2.31.0"})
        assert changes[0]["current"] == "(absent)"

    def test_detects_removed_package(self):
        changes = check_updates.diff_pins({"requests": "2.28.0"}, {})
        assert changes[0]["latest"] == "(removed)"

    def test_multiple_changes(self):
        current = {"a": "1.0", "b": "2.0", "c": "3.0"}
        upgraded = {"a": "1.1", "b": "2.0", "d": "4.0"}
        changes = check_updates.diff_pins(current, upgraded)
        packages = {c["package"] for c in changes}
        assert "a" in packages
        assert "c" in packages
        assert "d" in packages
        assert "b" not in packages

    def test_result_sorted_by_package_name(self):
        current = {"z": "1.0", "a": "1.0", "m": "1.0"}
        upgraded = {"z": "2.0", "a": "2.0", "m": "2.0"}
        changes = check_updates.diff_pins(current, upgraded)
        names = [c["package"] for c in changes]
        assert names == sorted(names)


# ---------------------------------------------------------------------------
# compile_upgraded
# ---------------------------------------------------------------------------


class TestCompileUpgraded:
    def test_failure_appends_to_errors(self, tmp_path):
        in_file = tmp_path / "requirements.in"
        in_file.write_text("requests\n")
        out_file = tmp_path / "upgraded.txt"
        errors: list[dict] = []

        with patch("subprocess.run") as mock_run:
            mock_run.return_value = MagicMock(returncode=1, stderr="compile error\n")
            result = check_updates.compile_upgraded(in_file, out_file, errors)

        assert result is False
        assert len(errors) == 1
        assert errors[0]["file"] == str(in_file)

    def test_success_returns_true(self, tmp_path):
        in_file = tmp_path / "requirements.in"
        in_file.write_text("requests\n")
        out_file = tmp_path / "upgraded.txt"
        errors: list[dict] = []

        def fake_run(_cmd, **_kwargs):
            out_file.write_text("requests==2.31.0\n")
            return MagicMock(returncode=0, stderr="", stdout="")

        with patch("subprocess.run", side_effect=fake_run):
            result = check_updates.compile_upgraded(in_file, out_file, errors)

        assert result is True
        assert errors == []

    def test_failure_stderr_is_truncated_to_last_20_lines(self, tmp_path):
        """Error capture keeps only the tail of stderr to bound report size."""
        in_file = tmp_path / "requirements.in"
        in_file.write_text("requests\n")
        out_file = tmp_path / "upgraded.txt"
        errors: list[dict] = []

        # 50 lines of stderr; only the last 20 must be retained.
        long_stderr = "\n".join(f"error line {i}" for i in range(50))
        with patch("subprocess.run") as mock_run:
            mock_run.return_value = MagicMock(returncode=1, stderr=long_stderr)
            check_updates.compile_upgraded(in_file, out_file, errors)

        assert len(errors) == 1
        stderr_tail = errors[0]["stderr"]
        assert len(stderr_tail) == 20
        # The tail must end with line 49, the very last line.
        assert "error line 49" in stderr_tail[-1]

    def test_command_does_not_use_shell(self, tmp_path):
        """``subprocess.run`` must receive a list, never shell=True."""
        in_file = tmp_path / "requirements.in"
        in_file.write_text("requests\n")
        out_file = tmp_path / "upgraded.txt"
        errors: list[dict] = []

        with patch("subprocess.run") as mock_run:
            mock_run.return_value = MagicMock(returncode=0, stderr="", stdout="")
            check_updates.compile_upgraded(in_file, out_file, errors)

        kwargs = mock_run.call_args.kwargs
        # shell=True would be a critical injection path; verify it's never set.
        assert kwargs.get("shell", False) is False
        # And the first positional arg is a list (argv form).
        assert isinstance(mock_run.call_args.args[0], list)


# ---------------------------------------------------------------------------
# main()
# ---------------------------------------------------------------------------


class TestMain:
    def test_skips_missing_txt_file(self, tmp_path, monkeypatch):
        in_file = tmp_path / "requirements.in"
        in_file.write_text("requests\n")
        monkeypatch.setenv("ALL_FILES", json.dumps([str(in_file)]))
        monkeypatch.setenv("REPORTS_DIR", str(tmp_path))
        check_updates.REPORTS = tmp_path
        rc = check_updates.main()
        assert rc == 0
        updates = json.loads((tmp_path / "updates.json").read_text())
        assert updates == {}

    def test_returns_one_on_compile_errors(self, tmp_path, monkeypatch):
        in_file = tmp_path / "requirements.in"
        in_file.write_text("requests\n")
        (tmp_path / "requirements.txt").write_text("requests==2.28.0\n")
        monkeypatch.setenv("ALL_FILES", json.dumps([str(in_file)]))
        monkeypatch.setenv("REPORTS_DIR", str(tmp_path))
        check_updates.REPORTS = tmp_path

        with patch("subprocess.run") as mock_run:
            mock_run.return_value = MagicMock(
                returncode=1, stderr="pip-compile error", stdout=""
            )
            rc = check_updates.main()
        assert rc == 1

    def test_detects_upgrade_between_current_and_upgraded(self, tmp_path, monkeypatch):
        in_file = tmp_path / "requirements.in"
        in_file.write_text("requests\n")
        (tmp_path / "requirements.txt").write_text("requests==2.28.0\n")
        monkeypatch.setenv("ALL_FILES", json.dumps([str(in_file)]))
        monkeypatch.setenv("REPORTS_DIR", str(tmp_path))
        check_updates.REPORTS = tmp_path

        def fake_run(cmd, **_kwargs):
            out_flag = "--output-file"
            if out_flag in cmd:
                idx = cmd.index(out_flag)
                Path(cmd[idx + 1]).write_text("requests==2.31.0\n")
            return MagicMock(returncode=0, stderr="", stdout="")

        with patch("subprocess.run", side_effect=fake_run):
            rc = check_updates.main()

        assert rc == 0
        updates = json.loads((tmp_path / "updates.json").read_text())
        assert len(updates) > 0

    def test_empty_all_files_returns_zero(self, tmp_path, monkeypatch):
        monkeypatch.setenv("ALL_FILES", "[]")
        monkeypatch.setenv("REPORTS_DIR", str(tmp_path))
        check_updates.REPORTS = tmp_path
        assert check_updates.main() == 0

    def test_writes_updates_and_errors_json(self, tmp_path, monkeypatch):
        monkeypatch.setenv("ALL_FILES", "[]")
        monkeypatch.setenv("REPORTS_DIR", str(tmp_path))
        check_updates.REPORTS = tmp_path
        check_updates.main()
        assert (tmp_path / "updates.json").exists()
        assert (tmp_path / "pip_compile_errors.json").exists()
